active_update_checkers:
  dockerhub_fetcher:
    interval: "30s"
    retry_time: "22s"
    kind: "dockerhub"

updaters:
  swarm:
    kind: "swarm"

services:
  skywire-manager:
    official_name: "skywire-manager"
    local_name: "nodes_skywire-manager"
    repository: "/skycoin/skywire"
    check_tag: ""
    active_update_checker: "dockerhub_fetcher"
    updater: "swarm"

  skywire-node:
    official_name: "skywire-node"
    local_name: "nodes_skywire-node"
    repository: "/skycoin/skywire"
    check_tag: ""
    active_update_checker: "dockerhub_fetcher"
    updater: "swarm"
