language: go
  go_import_path: github.com/skycoin/services/autoupdater
  before_install:
    - openssl aes-256-cbc -K $encrypted_85fc5370cc28_key -iv $encrypted_85fc5370cc28_iv
    -in ./.travis/id_rsa.deploy.enc -out ./.travis/id_rsa.deploy -d
  go: 1.10.3
  sudo: required
  install: true
  script:
    - cd ./autoupdater
    - go test ./...
    - cd ./cmd/autoupdater
    - go build
  after_success:
    - sh ../travis/deploy.sh
